app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
   return view('welcome');
});

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'auth.check'], function () {
    Route::get('categories', ['as' => 'categories.index', 'uses' => 'Admin\CategoriesController@index']);
    Route::get('categories/create', ['as' => 'categories.create', 'uses' => 'Admin\CategoriesController@create']);
    Route::post('categories/store', ['as' => 'categories.store', 'uses' => 'Admin\CategoriesController@store']);
    Route::get('categories/edit/{id}', ['as' => 'categories.edit', 'uses' => 'Admin\CategoriesController@edit']);
    Route::put('categories/update/{id}', ['as' => 'categories.update', 'uses' => 'Admin\CategoriesController@update']);
    Route::get('categories/destroy/{id}', ['as' => 'categories.destroy', 'uses' => 'Admin\CategoriesController@destroy']);

    Route::get('products', ['as' => 'products.index', 'uses' => 'Admin\ProductsController@index']);
    Route::get('products/create', ['as' => 'products.create', 'uses' => 'Admin\ProductsController@create']);
    Route::post('products/store', ['as' => 'products.store', 'uses' => 'Admin\ProductsController@store']);
    Route::get('products/edit/{id}', ['as' => 'products.edit', 'uses' => 'Admin\ProductsController@edit']);
    Route::put('products/update/{id}', ['as' => 'products.update', 'uses' => 'Admin\ProductsController@update']);
    Route::get('products/destroy/{id}', ['as' => 'products.destroy', 'uses' => 'Admin\ProductsController@destroy']);

    Route::get('clients', ['as' => 'clients.index', 'uses' => 'Admin\ClientsController@index']);
    Route::get('clients/create', ['as' => 'clients.create', 'uses' => 'Admin\ClientsController@create']);
    Route::post('clients/store', ['as' => 'clients.store', 'uses' => 'Admin\ClientsController@store']);
    Route::get('clients/edit/{id}', ['as' => 'clients.edit', 'uses' => 'Admin\ClientsController@edit']);
    Route::put('clients/update/{id}', ['as' => 'clients.update', 'uses' => 'Admin\ClientsController@update']);
    Route::get('clients/destroy/{id}', ['as' => 'clients.destroy', 'uses' => 'Admin\ClientsController@destroy']);

    Route::get('orders', ['as' => 'orders.index', 'uses' => 'Admin\OrdersController@index']);
    Route::get('orders/{id}', ['as' => 'orders.edit', 'uses' => 'Admin\OrdersController@edit']);
    Route::put('orders/update/{id}', ['as' => 'orders.update', 'uses' => 'Admin\OrdersController@update']);
    Route::get('orders/destroy/{id}', ['as' => 'orders.destroy', 'uses' => 'Admin\OrdersController@destroy']);

    Route::get('cupoms', ['as' => 'cupoms.index', 'uses' => 'Admin\CupomsController@index']);
    Route::get('cupoms/create', ['as' => 'cupoms.create', 'uses' => 'Admin\CupomsController@create']);
    Route::post('cupoms/store', ['as' => 'cupoms.store', 'uses' => 'Admin\CupomsController@store']);
    Route::get('cupoms/edit/{id}', ['as' => 'cupoms.edit', 'uses' => 'Admin\CupomsController@edit']);
    Route::put('cupoms/update/{id}', ['as' => 'cupoms.update', 'uses' => 'Admin\CupomsController@update']);
    Route::get('cupoms/destroy/{id}', ['as' => 'cupoms.destroy', 'uses' => 'Admin\CupomsController@destroy']);

});


Route::auth();

Route::get('/home', 'HomeController@index');

app/Models/Client.php
<?php

namespace CodeDelivery\Models;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Client extends Model implements Transformable
{
    use TransformableTrait;

    protected $fillable = [
        'user_id',
        'phone',
        'address',
        'city',
        'state',
        'zipcode',
    ];

    public function products()
    {
        return $this->hasMany(Product::class);
    }

    public function user()
    {
        return $this->hasOne(User::class, 'id', 'user_id');
    }

}

app/Http/Controllers/Admin/ClientsController.php
<?php

namespace CodeDelivery\Http\Controllers\Admin;

use CodeDelivery\Http\Controllers\Controller;
use CodeDelivery\Http\Requests;
use CodeDelivery\Http\Requests\Admin\ClientRequest;
use CodeDelivery\Repositories\ClientRepository;
use CodeDelivery\Repositories\UserRepository;
use CodeDelivery\Services\ClientService;


class ClientsController extends Controller
{
    /**
     * @var ProductRepository
     */
    private $repository;

    /**
     * @var UserRepository
     */
    private $userRepository;
    /**
     * @var ClientService
     */
    private $clientService;

    public function __construct(
        ClientRepository $repository,
        UserRepository $userRepository,
        ClientService $clientService)
    {

        $this->repository = $repository;
        $this->userRepository = $userRepository;
        $this->clientService = $clientService;
    }

    public function index()
    {
        $clients = $this->repository->paginate();

        return view('admin.clients.index', compact('clients'));
    }

    public function create()
    {
        $users = $this->userRepository->lists('name', 'id');
        return view('admin.clients.create', compact('users'));
    }

    public function store(ClientRequest $request)
    {
        $this->clientService->create($request->all());
        return redirect()->route('admin.clients.index');
    }
    public function edit($id)
    {
        $client = $this->repository->find($id);
        return view('admin.clients.edit', compact('client'));
    }

    public function update(ClientRequest $request, $id)
    {
        $this->clientService->update($request->all(), $id);
        return redirect()->route('admin.clients.index');
    }

    public function destroy($id)
    {
        $this->repository->delete($id);
        return redirect()->route('admin.clients.index');
    }
}

resources/views/admin/clients/_form.blade.php
{{ Form::hidden('user[id]', null) }}
<div class="form-group">
    {{ Form::label('name', 'Nome', array('class' => 'control-label')) }}
    {{ Form::text('user[name]', null,  array( 'class' => 'form-control')) }}
</div>

<div class="form-group">
    {{ Form::label('email', 'E-mail', array('class' => 'control-label')) }}
    {{ Form::text('user[email]', null,  array( 'class' => 'form-control')) }}
</div>

<div class="form-group">
    {{ Form::label('phone', 'Telefone', array('class' => 'control-label')) }}
    {{ Form::text('phone', null , array( 'class' => 'form-control')) }}
</div>

<div class="form-group">
    {{ Form::label('address', 'Endereço', array('class' => 'control-label')) }}
    {{ Form::textarea('address', null , array( 'class' => 'form-control')) }}
</div>

<div class="form-group">
    {{ Form::label('city', 'Cidade', array('class' => 'control-label')) }}
    {{ Form::text('city', null , array( 'class' => 'form-control')) }}
</div>

<div class="form-group">
    {{ Form::label('state', 'Estade', array('class' => 'control-label')) }}
    {{ Form::text('state', null , array( 'class' => 'form-control')) }}
</div>

<div class="form-group">
    {{ Form::label('zipcode', 'CEP', array('class' => 'control-label')) }}
    {{ Form::text('zipcode', null , array( 'class' => 'form-control')) }}
</div>

resources/views/admin/clients/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">

    <h3>Novo cliente</h3>

    @include('errors._ckeck')

    {!! Form::open(['route' => 'admin.clients.store']) !!}

    @include('admin.clients._form')

    <div class="form-group">
        {{ Form::submit('Criar', array('class' => 'btn btn-primary')) }}
    </div>
    {!! Form::close() !!}

</div>

@endsection

resources/views/admin/clients/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container">

    <h3>Editar cliente: {{ $client->user->name }}</h3>

    @include('errors._ckeck')

    {!! Form::model($client, ['route' => ['admin.clients.update', $client->id], 'method' => 'put']) !!}

    @include('admin.clients._form')

    <div class="form-group">
        {{ Form::submit('Salvar', array('class' => 'btn btn-primary')) }}
    </div>
    {!! Form::close() !!}

</div>

@endsection

resources/views/admin/clients/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">

        <h3>Clientes</h3>

        <a href="{{ route('admin.clients.create') }}" class="btn btn-success">Novo cliente</a>
        <br>
        <br>

        <table class="table table-bordered">
            <thead>
            <tr>
                <th width="5%">#</th>
                <th width="20%">Nome</th>
                <th width="15%">E-mail</th>
                <th width="10%">Telefone</th>
                <th width="10%">Cidade</th>
                <th width="20%">Açao</th>
            </tr>
            </thead>
            <tbody>
            @foreach($clients as $client)
                <tr>
                    <td>{{ $client->id }}</td>
                    <td>{{ $client->user->name }}</td>
                    <td>{{ $client->user->email }}</td>
                    <td>{{ $client->phone }}</td>
                    <td>{{ $client->city }}</td>
                    <td>
                        <a href="{{ route('admin.clients.edit', ['id' => $client->id]) }}" class="btn btn-default btn-sm">Editar</a>
                        <a href="{{ route('admin.clients.destroy', ['id' => $client->id]) }}" class="btn btn-danger btn-sm">Excluir</a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        {{ $clients->render() }}
    </div>

@endsection