app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
   return view('welcome');
});

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'auth.check'], function () {
    Route::get('categories', ['as' => 'categories.index', 'uses' => 'Admin\CategoriesController@index']);
    Route::get('categories/create', ['as' => 'categories.create', 'uses' => 'Admin\CategoriesController@create']);
    Route::post('categories/store', ['as' => 'categories.store', 'uses' => 'Admin\CategoriesController@store']);
    Route::get('categories/edit/{id}', ['as' => 'categories.edit', 'uses' => 'Admin\CategoriesController@edit']);
    Route::put('categories/update/{id}', ['as' => 'categories.update', 'uses' => 'Admin\CategoriesController@update']);
    Route::get('categories/destroy/{id}', ['as' => 'categories.destroy', 'uses' => 'Admin\CategoriesController@destroy']);

    Route::get('products', ['as' => 'products.index', 'uses' => 'Admin\ProductsController@index']);
    Route::get('products/create', ['as' => 'products.create', 'uses' => 'Admin\ProductsController@create']);
    Route::post('products/store', ['as' => 'products.store', 'uses' => 'Admin\ProductsController@store']);
    Route::get('products/edit/{id}', ['as' => 'products.edit', 'uses' => 'Admin\ProductsController@edit']);
    Route::put('products/update/{id}', ['as' => 'products.update', 'uses' => 'Admin\ProductsController@update']);
    Route::get('products/destroy/{id}', ['as' => 'products.destroy', 'uses' => 'Admin\ProductsController@destroy']);

    Route::get('clients', ['as' => 'clients.index', 'uses' => 'Admin\ClientsController@index']);
    Route::get('clients/create', ['as' => 'clients.create', 'uses' => 'Admin\ClientsController@create']);
    Route::post('clients/store', ['as' => 'clients.store', 'uses' => 'Admin\ClientsController@store']);
    Route::get('clients/edit/{id}', ['as' => 'clients.edit', 'uses' => 'Admin\ClientsController@edit']);
    Route::put('clients/update/{id}', ['as' => 'clients.update', 'uses' => 'Admin\ClientsController@update']);
    Route::get('clients/destroy/{id}', ['as' => 'clients.destroy', 'uses' => 'Admin\ClientsController@destroy']);

    Route::get('orders', ['as' => 'orders.index', 'uses' => 'Admin\OrdersController@index']);
    Route::get('orders/{id}', ['as' => 'orders.edit', 'uses' => 'Admin\OrdersController@edit']);
    Route::put('orders/update/{id}', ['as' => 'orders.update', 'uses' => 'Admin\OrdersController@update']);
    Route::get('orders/destroy/{id}', ['as' => 'orders.destroy', 'uses' => 'Admin\OrdersController@destroy']);

    Route::get('cupoms', ['as' => 'cupoms.index', 'uses' => 'Admin\CupomsController@index']);
    Route::get('cupoms/create', ['as' => 'cupoms.create', 'uses' => 'Admin\CupomsController@create']);
    Route::post('cupoms/store', ['as' => 'cupoms.store', 'uses' => 'Admin\CupomsController@store']);
    Route::get('cupoms/edit/{id}', ['as' => 'cupoms.edit', 'uses' => 'Admin\CupomsController@edit']);
    Route::put('cupoms/update/{id}', ['as' => 'cupoms.update', 'uses' => 'Admin\CupomsController@update']);
    Route::get('cupoms/destroy/{id}', ['as' => 'cupoms.destroy', 'uses' => 'Admin\CupomsController@destroy']);

});


Route::auth();

Route::get('/home', 'HomeController@index');

app/Models/Order.php
<?php

namespace CodeDelivery\Models;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Order extends Model implements Transformable
{
    use TransformableTrait;

    protected $fillable = [
        'client_id',
        'user_deliveryman_id',
        'total',
        'status',
    ];

    public function items()
    {
        return $this->hasMany(OrderItem::class);
    }

    public function client()
    {
        return $this->belongsTo(Client::class);
    }

    public function deliveryman()
    {
        return $this->belongsTo(User::class, 'user_deliveryman_id', 'id');
    }

}

app/Http/Controllers/Admin/OrdersController.php
<?php

namespace CodeDelivery\Http\Controllers\Admin;


use CodeDelivery\Http\Controllers\Controller;
use CodeDelivery\Repositories\OrderRepository;
use CodeDelivery\Repositories\UserRepository;
use Illuminate\Http\Request;

class OrdersController extends Controller
{

    /**
     * @var OrderRepository
     */
    private $repository;

    public function __construct(OrderRepository $repository)
    {

        $this->repository = $repository;
    }

    public function index()
    {
        $orders = $this->repository->paginate();
        return view('admin.orders.index', compact('orders', 'list_status'));
    }

    public function edit($id, UserRepository $userRepository)
    {
        $order = $this->repository->find($id);
        $list_status = [
            0 => 'Pendente',
            1 => 'Em Trânsito',
            2 => 'Entregue',
            3 => 'Cancelado',
        ];
        $deliveryman = $userRepository->getDeliveryman();
        return view('admin.orders.edit', compact('order', 'list_status', 'deliveryman'));
    }

    public function update(Request $request, $id)
    {
        $this->repository->update($request->all(), $id);
        return redirect()->route('admin.orders.index');
    }

    public function destroy($id)
    {
        $this->repository->delete($id);
        return redirect()->route('admin.orders.index');
    }

}

resources/views/admin/orders/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">

        <h3>Pedido nº #{{ $order->id }}, Valor: R$ {{ $order->total }}</h3>
        <h4><b>Cliente:</b> {{ $order->client->user->name }}</h4>
        <h5>
            <p>
                <b>Entregar em:</b><br>
                {{ $order->client->address }}<br>
                {{ $order->client->city }} - {{ $order->client->state }} - {{ $order->client->zipcode }}<br>
                <b>Telefone:</b> {{ $order->client->phone }}
            </p>
        </h5>
        {!! Form::model($order, ['route' => ['admin.orders.update', $order->id], 'method' => 'put']) !!}
        <div class="form-group">
            {{ Form::label('status', 'Status', array('class' => 'control-label')) }}
            {{ Form::select('status', $list_status, null , array( 'class' => 'form-control')) }}
        </div>
        <div class="form-group">
            {{ Form::label('user_deliveryman_id', 'Entregador', array('class' => 'control-label')) }}
            {{ Form::select('user_deliveryman_id', $deliveryman, null , array( 'class' => 'form-control')) }}
        </div>
        <div class="form-group">
            {{ Form::submit('Salvar', array('class' => 'btn btn-primary')) }}
        </div>
        {!! Form::close() !!}
    </div>

@endsection

resources/views/admin/orders/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">

        <h3>Pedidos</h3>

        <table class="table table-bordered">
            <thead>
            <tr>
                <th>#</th>
                <th>Total</th>
                <th>Data</th>
                <th>Itens</th>
                <th>Entregador</th>
                <th>Status</th>
                <th>Açao</th>
            </tr>
            </thead>
            <tbody>
            @foreach($orders as $order)
                <tr>
                    <td>#{{ $order->id }}</td>
                    <td>{{ $order->total }}</td>
                    <td>{{ $order->created_at }}</td>
                    <td>
                        <ul>
                        @foreach($order->items as $item)
                            <li>{{ $item->product->name }} - {{ $item->price }}</li>
                        @endforeach
                        </ul>
                    </td>
                    <td>
                        @if($order->deliveryman)
                            {{ $order->deliveryman->name }}
                        @else
                            --
                        @endif
                    </td>
                    <td>{{ $order->status }}</td>
                    <td>
                        <a href="{{ route('admin.orders.edit', ['id' => $order->id]) }}" class="btn btn-default btn-sm">Editar</a>
                        <a href="{{ route('admin.orders.destroy', ['id' => $order->id]) }}" class="btn btn-danger btn-sm">Excluir</a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        {{ $orders->render() }}
    </div>

@endsection