app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
   return view('welcome');
});

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'auth.check'], function () {
    Route::get('categories', ['as' => 'categories.index', 'uses' => 'Admin\CategoriesController@index']);
    Route::get('categories/create', ['as' => 'categories.create', 'uses' => 'Admin\CategoriesController@create']);
    Route::post('categories/store', ['as' => 'categories.store', 'uses' => 'Admin\CategoriesController@store']);
    Route::get('categories/edit/{id}', ['as' => 'categories.edit', 'uses' => 'Admin\CategoriesController@edit']);
    Route::put('categories/update/{id}', ['as' => 'categories.update', 'uses' => 'Admin\CategoriesController@update']);
    Route::get('categories/destroy/{id}', ['as' => 'categories.destroy', 'uses' => 'Admin\CategoriesController@destroy']);

    Route::get('products', ['as' => 'products.index', 'uses' => 'Admin\ProductsController@index']);
    Route::get('products/create', ['as' => 'products.create', 'uses' => 'Admin\ProductsController@create']);
    Route::post('products/store', ['as' => 'products.store', 'uses' => 'Admin\ProductsController@store']);
    Route::get('products/edit/{id}', ['as' => 'products.edit', 'uses' => 'Admin\ProductsController@edit']);
    Route::put('products/update/{id}', ['as' => 'products.update', 'uses' => 'Admin\ProductsController@update']);
    Route::get('products/destroy/{id}', ['as' => 'products.destroy', 'uses' => 'Admin\ProductsController@destroy']);

    Route::get('clients', ['as' => 'clients.index', 'uses' => 'Admin\ClientsController@index']);
    Route::get('clients/create', ['as' => 'clients.create', 'uses' => 'Admin\ClientsController@create']);
    Route::post('clients/store', ['as' => 'clients.store', 'uses' => 'Admin\ClientsController@store']);
    Route::get('clients/edit/{id}', ['as' => 'clients.edit', 'uses' => 'Admin\ClientsController@edit']);
    Route::put('clients/update/{id}', ['as' => 'clients.update', 'uses' => 'Admin\ClientsController@update']);
    Route::get('clients/destroy/{id}', ['as' => 'clients.destroy', 'uses' => 'Admin\ClientsController@destroy']);

    Route::get('orders', ['as' => 'orders.index', 'uses' => 'Admin\OrdersController@index']);
    Route::get('orders/{id}', ['as' => 'orders.edit', 'uses' => 'Admin\OrdersController@edit']);
    Route::put('orders/update/{id}', ['as' => 'orders.update', 'uses' => 'Admin\OrdersController@update']);
    Route::get('orders/destroy/{id}', ['as' => 'orders.destroy', 'uses' => 'Admin\OrdersController@destroy']);

    Route::get('cupoms', ['as' => 'cupoms.index', 'uses' => 'Admin\CupomsController@index']);
    Route::get('cupoms/create', ['as' => 'cupoms.create', 'uses' => 'Admin\CupomsController@create']);
    Route::post('cupoms/store', ['as' => 'cupoms.store', 'uses' => 'Admin\CupomsController@store']);
    Route::get('cupoms/edit/{id}', ['as' => 'cupoms.edit', 'uses' => 'Admin\CupomsController@edit']);
    Route::put('cupoms/update/{id}', ['as' => 'cupoms.update', 'uses' => 'Admin\CupomsController@update']);
    Route::get('cupoms/destroy/{id}', ['as' => 'cupoms.destroy', 'uses' => 'Admin\CupomsController@destroy']);

});


Route::auth();

Route::get('/home', 'HomeController@index');

app/Models/Category.php
<?php

namespace CodeDelivery\Models;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Category extends Model implements Transformable
{
    use TransformableTrait;

    protected $fillable = [
        'name',
    ];

    public function products()
    {
        return $this->hasMany(Product::class);
    }

}

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace CodeDelivery\Http\Controllers\Admin;

use CodeDelivery\Http\Controllers\Controller;
use CodeDelivery\Http\Requests;
use CodeDelivery\Http\Requests\Admin\CategoryRequest;
use CodeDelivery\Repositories\CategoryRepository;

class CategoriesController extends Controller
{
    /**
     * @var CategoryRepository
     */
    private $repository;

    public function __construct(CategoryRepository $repository)
    {

        $this->repository = $repository;
    }

    public function index()
    {
        $categories = $this->repository->paginate();

        return view('admin.categories.index', compact('categories'));
    }

    public function create()
    {
        return view('admin.categories.create');
    }

    public function store(CategoryRequest $request)
    {
        $this->repository->create($request->all());
        return redirect()->route('admin.categories.index');
    }
    public function edit($id)
    {
        $category = $this->repository->find($id);
        return view('admin.categories.edit', compact('category'));
    }

    public function update(CategoryRequest $request, $id)
    {
        $this->repository->update($request->all(), $id);
        return redirect()->route('admin.categories.index');
    }

    public function destroy($id)
    {
        $this->repository->delete($id);
        return redirect()->route('admin.categories.index');
    }
}

resources/views/admin/categories/_form.blade.php
<!-- Name Form Field -->
<div class="form-group">
    {{ Form::label('name', 'Nome', array('class' => 'control-label')) }}
    {{ Form::text('name', null , array( 'class' => 'form-control')) }}
</div>

resources/views/admin/categories/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">

    <h3>Nova categoria</h3>

    @include('errors._ckeck')

    {!! Form::open(['route' => 'admin.categories.store']) !!}

    @include('admin.categories._form')

    <div class="form-group">
        {{ Form::submit('Criar', array('class' => 'btn btn-primary')) }}
    </div>
    {!! Form::close() !!}

</div>

@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container">

    <h3>Editar categoria: {{ $category->name }}</h3>

    @include('errors._ckeck')

    {!! Form::model($category, ['route' => ['admin.categories.update', $category->id], 'method' => 'put']) !!}

    @include('admin.categories._form')

    <div class="form-group">
        {{ Form::submit('Salvar', array('class' => 'btn btn-primary')) }}
    </div>
    {!! Form::close() !!}

</div>

@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">

    <h3>Categorias</h3>

    <a href="{{ route('admin.categories.create') }}" class="btn btn-success">Nova categoria</a>
    <br>
    <br>

    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="5%">#</th>
            <th width="60%">Nome</th>
            <th width="35%">Açao</th>
        </tr>
        </thead>
        <tbody>
        @foreach($categories as $category)
        <tr>
            <td>{{ $category->id }}</td>
            <td>{{ $category->name }}</td>
            <td>
                <a href="{{ route('admin.categories.edit', ['id' => $category->id]) }}" class="btn btn-default btn-sm">Editar</a>
                <a href="{{ route('admin.categories.destroy', ['id' => $category->id]) }}" class="btn btn-danger btn-sm">Excluir</a>
            </td>
        </tr>
        @endforeach
        </tbody>
    </table>
    {{ $categories->render() }}
</div>

@endsection